spring.application.name=coldtrace-api-gateway
server.port=${PORT:8080}
coldtrace.monitoring.url=${MONITORING_URL:http://localhost:8083}
coldtrace.backend.url=${BACKEND_URL:http://localhost:8090}
coldtrace.alert.url=${ALERT_URL:http://localhost:8084}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.cloud.gateway.httpclient.connect-timeout=3000
spring.cloud.gateway.httpclient.response-timeout=5s
